[package]
name = "class03_01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ran = "1.0.7"
scanrs = "0.3.0"
